server:
   port: 80
spring:
   resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
   thymeleaf:
      cache: false
      characterEncoding: UTF-8
      check-template: true
      check-template-location: true
      encoding: UTF-8
      prefix: classpath:/templates/
      servlet:
         content-type: text/html; charset=utf-8
      suffix: .html
   data:
      mongodb:
         uri: mongodb://credit:5913215@192.168.0.28:27011,192.168.0.28:27012,192.168.0.28:27013/credit